In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv("dataset_Facebook.csv" , sep=';')

In [49]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [50]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [51]:
df['Type'].values

array(['Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Status', 'Photo',
       'Photo', 'Status', 'Photo', 'Status', 'Photo', 'Photo', 'Photo',
       'Photo', 'Status', 'Photo', 'Photo', 'Status', 'Photo', 'Photo',
       'Photo', 'Link', 'Photo', 'Status', 'Status', 'Status', 'Photo',
       'Photo', 'Video', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Status', 'Photo', 'Status', 'Link',
       'Photo', 'Link', 'Photo', 'Link', 'Status', 'Link', 'Photo',
       'Link', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Video',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Video', 'Status', 'Photo', 'Video', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Status', 'Photo', 'Photo', 'Photo',
       'Status', 'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Status', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Status', 'Photo', 'Status', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Link', 'Photo', 'Status', 'Photo',
       'Link', 'Status', 'Status', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Status', 'Link', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Status', 'Photo', 'Photo',
       'Status', 'Photo', 'Photo', 'Photo', 'Photo', 'Status', 'Photo',
       'Photo', 'Video', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Status',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Status', 'Photo', 'Photo', 'Photo', 'Photo', 'Status', 'Status',
       'Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Status', 'Photo', 'Photo', 'Status', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Status', 'Video', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Status', 'Photo', 'Video', 'Photo', 'Photo',
       'Photo', 'Photo', 'Status', 'Photo', 'Photo', 'Status', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Status', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Status', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Status', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Status', 'Link', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Link', 'Photo', 'Photo',
       'Photo', 'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Status', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Link', 'Photo',
       'Photo', 'Photo', 'Photo', 'Link', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Link', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Link', 'Photo',
       'Photo', 'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Link', 'Photo', 'Photo', 'Photo', 'Photo',
       'Photo', 'Photo', 'Photo'], dtype=object)

In [52]:
sub1 = df[df['Type']== 'Photo']

In [53]:
sub1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [54]:
sub1.shape

(426, 19)

In [55]:
sub2 = df[df['Type']== 'Status']
sub2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
40,138895,Status,2,12,6,11,0.0,13280,24198,2055,1912,2720,17627,9344,1716,7,216.0,39.0,262
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
72,137893,Status,3,11,4,11,0.0,9056,16362,1006,847,1153,9562,5180,740,3,226.0,44.0,273
80,137177,Status,2,11,7,3,0.0,8728,17827,2295,2235,2828,15418,7344,2099,2,86.0,13.0,101
84,137177,Status,3,11,5,2,0.0,6692,13092,199,108,141,7549,3336,156,2,99.0,16.0,117
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
107,136736,Status,2,10,1,4,0.0,9504,19556,1132,1032,1512,16018,7616,981,17,193.0,28.0,238
109,136736,Status,2,10,7,3,0.0,13872,27468,2664,2570,3395,20198,10432,2252,4,217.0,50.0,271
121,136393,Status,2,10,7,9,0.0,15816,30514,2733,2654,3289,23584,11912,2361,6,186.0,40.0,232
138,136013,Status,2,10,5,3,0.0,8896,17202,1480,1426,1932,13838,7020,1292,0,129.0,25.0,154
141,136013,Status,3,10,3,10,0.0,13152,25666,2543,2438,3179,20547,10280,2278,2,227.0,36.0,265
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
148,135713,Status,2,10,7,4,0.0,10744,20691,1967,1877,2201,17502,8964,1834,3,148.0,28.0,179
163,135617,Status,2,9,6,4,0.0,11096,21080,1843,1724,2106,16095,8120,1604,4,243.0,41.0,288
172,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
175,135195,Status,2,9,6,10,1.0,13216,24738,2675,2584,2969,19599,10232,2342,2,165.0,22.0,189
180,134879,Status,2,9,4,4,1.0,9124,17776,1476,1397,1797,13887,7092,1331,20,150.0,29.0,199
202,132817,Status,2,8,3,2,1.0,9236,16054,1151,1130,1560,14014,7880,1075,2,53.0,15.0,70
217,131956,Status,2,8,2,12,0.0,14424,26000,304,286,383,25539,14056,291,41,15.0,1.0,57
222,131808,Status,2,8,7,4,0.0,8260,14305,997,953,1211,12905,7360,956,1,74.0,11.0,86
223,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
225,131808,Status,2,7,5,14,0.0,15296,25269,2827,2781,3627,22103,13296,2602,9,95.0,17.0,121
232,131630,Status,2,7,2,6,1.0,10824,20573,135,126,153,20030,10384,126,6,14.0,1.0,21
235,131300,Status,2,7,7,10,0.0,10956,19279,128,119,130,18838,10564,123,3,13.0,1.0,17
242,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
253,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
267,128032,Status,2,7,5,10,0.0,10188,16978,1473,1441,2136,14450,8536,1395,13,61.0,13.0,87
275,126424,Status,2,7,3,13,0.0,18320,31448,3742,3682,7854,25584,14920,3300,36,98.0,14.0,148
282,126345,Status,2,6,7,11,0.0,12044,20327,2240,2193,3599,17717,10400,2119,0,104.0,13.0,117
285,126141,Status,2,6,6,4,0.0,8628,14847,870,843,1692,11970,6796,774,4,72.0,18.0,94
334,119198,Status,2,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67
352,116435,Status,1,5,4,3,1.0,23832,42313,1701,1570,2838,37816,21352,1578,6,210.0,39.0,255
362,116091,Status,2,5,5,7,0.0,9232,16811,908,861,1967,12996,7200,843,1,129.0,36.0,166
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
416,104070,Status,1,3,3,15,0.0,9120,14759,951,937,1290,13246,8004,924,3,25.0,6.0,34

In [56]:
sub2.shape

(45, 19)

In [57]:
sub3 = df.iloc[0:100]
sub3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,137059,Photo,3,10,6,10,0.0,3090,5744,391,257,360,3521,1796,293,5,153.0,27.0,185
96,137059,Photo,1,10,6,3,0.0,1101,2548,324,287,2418,1284,704,220,3,51.0,11.0,65
97,137059,Photo,2,10,5,11,0.0,2819,5230,318,218,303,3128,1622,240,1,115.0,26.0,142
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
99,137020,Photo,1,10,4,10,0.0,12776,21893,785,539,881,13272,7800,575,12,328.0,90.0,430

In [58]:
sub3.shape

(100, 19)

In [59]:
sub4 = df.iloc[100 :]
sub4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
102,137020,Photo,3,10,3,10,0.0,1711,3174,288,245,339,2226,1118,205,2,63.0,14.0,79
103,137020,Photo,1,10,3,4,0.0,1388,2544,224,219,931,2161,1214,172,0,13.0,4.0,17
104,137020,Photo,1,10,2,11,1.0,2645,5472,357,315,482,4485,2101,265,4,59.0,9.0,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [60]:
sub5 = df[['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday','Post Hour', 'Paid']]
sub5

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid
0,139441,Photo,2,12,4,3,0.0
1,139441,Status,2,12,3,10,0.0
2,139441,Photo,3,12,3,3,0.0
3,139441,Photo,2,12,2,10,1.0
4,139441,Photo,2,12,2,3,0.0
...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0
496,81370,Photo,2,1,5,8,0.0
497,81370,Photo,1,1,5,2,0.0
498,81370,Photo,3,1,4,11,0.0
499,81370,Photo,2,1,4,4,NaN

In [61]:
sub6 = df[['Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions']]
sub6

,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [62]:
sub7 = df[['like', 'share', 'Total Interactions']]
sub7

       like  share  Total Interactions
0      79.0   17.0                 100
1     130.0   29.0                 164
2      66.0   14.0                  80
3    1572.0  147.0                1777
4     325.0   49.0                 393
..      ...    ...                 ...
495    53.0   26.0                  84
496    53.0   22.0                  75
497    93.0   18.0                 115
498    91.0   38.0                 136
499    91.0   28.0                 119

[500 rows x 3 columns]

In [63]:
sub1.shape

(426, 19)

In [64]:
sub2.shape

(45, 19)

In [65]:
merge1 = pd.concat([sub1 , sub2]) #row
merge1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,119198,Status,2,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67
352,116435,Status,1,5,4,3,1.0,23832,42313,1701,1570,2838,37816,21352,1578,6,210.0,39.0,255
362,116091,Status,2,5,5,7,0.0,9232,16811,908,861,1967,12996,7200,843,1,129.0,36.0,166
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
416,104070,Status,1,3,3,15,0.0,9120,14759,951,937,1290,13246,8004,924,3,25.0,6.0,34

In [66]:
sub3.shape

(100, 19)

In [67]:
sub4.shape

(400, 19)

In [68]:
merge2 = pd.concat([sub3 , sub4]) #roww
merge2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [69]:
merge2.shape

(500, 19)

In [70]:
sub5.shape

(500, 7)

In [71]:
sub6.shape

(500, 14)

In [72]:
merge3 = pd.concat([sub5 , sub6] , axis = 1) #column
merge3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Post Hour,Paid,Lifetime Post Total Reach,...,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,3,0.0,2752,...,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10,0.0,10460,...,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,3,0.0,2413,...,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,10,1.0,50128,...,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,3,0.0,7244,...,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,2,0.0,4684,...,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,8,0.0,3480,...,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,2,0.0,3778,...,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,11,0.0,4156,...,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4,NaN,4188,...,564,524,743,3861,2200,316,0,91.0,28.0,119

In [73]:
merge3.shape

(500, 21)

In [74]:
#sort

In [75]:
df.sort_values(by=['Category'])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84

In [76]:
df.sort_values(by=['Type'])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
55,138329,Video,1,11,6,2,1.0,16416,31950,459,411,539,21436,9568,363,2,65.0,14.0,81
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
243,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
74,137893,Video,1,11,3,11,0.0,13544,30235,517,458,667,26622,11760,447,2,99.0,13.0,114

In [77]:
df_copy = pd.DataFrame(data=df)

In [78]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [79]:
df_transposed = df_copy.transpose()
df_transposed

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [80]:
#pivot table

In [81]:
table = pd.pivot_table(data = df , values = ['Lifetime Post Total Impressions', 'Lifetime Engaged Users'] , index=['Type'])

In [82]:
table

        Lifetime Engaged Users  Lifetime Post Total Impressions
Type
Link                342.818182                     28725.454545
Photo               818.946009                     28994.497653
Status             2040.222222                     24244.466667
Video              1707.000000                    102622.428571

In [83]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [84]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [85]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [86]:
mean_paid = df['Paid'].mean()
mean_paid

np.float64(0.2785571142284569)

In [87]:

df['Paid'] = df['Paid'].fillna(mean_paid)

In [88]:
df['Paid'].isnull().sum()

np.int64(0)

In [89]:
mean_like = df['like'].mean()
mean_like

np.float64(177.94589178356713)

In [90]:
df['like'] = df['like'].fillna(mean_like)

In [91]:
df['like'].isnull().sum()

np.int64(0)

In [ ]:
#reshape 
numeric_data = df[["Page total likes", "Post Month", "Post Hour"]].head(6).values
print("Original shape:", numeric_data.shape)

reshaped_data = numeric_data.reshape(3, 6)
print("Reshaped to (3, 6):", reshaped_data.shape)
print(reshaped_data)

Original shape: (6, 3)
Reshaped to (3, 6): (3, 6)
[[139441     12      3 139441     12     10]
 [139441     12      3 139441     12     10]
 [139441     12      3 139441     12      9]]