In [54]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score , confusion_matrix

In [19]:
df = pd.read_csv("Heart_dataset.csv")

In [20]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [21]:
df.drop("Unnamed: 0" , axis=1)

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [22]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [23]:
df1 = df['Ca'].fillna(value=0.0)

In [24]:
df['Ca']=df1

In [25]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          2
AHD           0
dtype: int64

In [26]:
df["Thal"].unique()

array(['fixed', 'normal', 'reversable', nan], dtype=object)

In [27]:
df['Thal'].map({'fixed':1,'normal':2,'reversable':3})

0      1.0
1      2.0
2      3.0
3      2.0
4      2.0
      ...
298    3.0
299    3.0
300    3.0
301    2.0
302    2.0
Name: Thal, Length: 303, dtype: float64

In [28]:
df2 = df['Thal'].fillna(value=0.0)
df['Thal']=df2

In [29]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [30]:
le = LabelEncoder()

In [31]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,0.0,normal,No

In [32]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [34]:
chest_num  = le.fit_transform(df['ChestPain'])

In [35]:
df['ChestPain'] = chest_num

In [45]:
Thal_num = le.fit_transform(df["Thal"].astype(str))
Thal_num

array([1, 2, 3, 2, 2, 2, 2, 2, 3, 3, 1, 2, 1, 3, 3, 2, 3, 2, 2, 2, 2, 2,
       2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2, 3, 1, 3, 2, 3, 3, 2, 2,
       2, 3, 2, 3, 2, 2, 2, 3, 2, 2, 3, 3, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3,
       2, 3, 3, 2, 2, 3, 3, 1, 2, 2, 3, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 0,
       2, 2, 2, 3, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 2, 1, 3, 3, 1, 2, 2, 3, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 2, 3, 3,
       2, 2, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, 2, 3, 2, 3, 3,
       2, 2, 3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 3, 2, 2, 1, 3,
       3, 1, 2, 2, 3, 3, 2, 3, 2, 2, 3, 1, 3, 3, 2, 3, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 2, 3, 2, 1, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 1, 0, 1, 3, 2, 3, 1, 3, 2, 2, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 1,
       1, 3, 3, 2, 3, 2, 1, 3, 2, 2, 1, 3, 3, 3, 3, 2, 2])

In [46]:
df['Thal'] = Thal_num

In [49]:
ahd_num = le.fit_transform(df["AHD"])
df['AHD'] = ahd_num

In [50]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,1,0
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,2,1
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,3,1
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,2,0
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,3,1
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,3,1
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,3,1
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,2,1
302,303,38,1,1,138,175,0,0,173,0,0.0,1,0.0,2,0

In [51]:
df['Oldpeak'] = df['Oldpeak'].astype(int)

In [52]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2,3,0.0,1,0
1,2,67,1,0,160,286,0,2,108,1,1,2,3.0,2,1
2,3,67,1,0,120,229,0,2,129,1,2,2,2.0,3,1
3,4,37,1,1,130,250,0,0,187,0,3,3,0.0,2,0
4,5,41,0,2,130,204,0,2,172,0,1,1,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1,2,0.0,3,1
299,300,68,1,0,144,193,1,0,141,0,3,2,2.0,3,1
300,301,57,1,0,130,131,0,0,115,1,1,2,1.0,3,1
301,302,57,0,2,130,236,0,2,174,0,0,2,1.0,2,1
302,303,38,1,1,138,175,0,0,173,0,0,1,0.0,2,0

In [53]:
X = df.drop("AHD" , axis=1)
Y = df["AHD"]

In [55]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytestt = train_test_split(X,Y,test_size=0.2,random_state=42)

In [57]:
clf  = DecisionTreeClassifier()

In [58]:
clf.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
clf.predict(xtrain)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [60]:
ypred = clf.predict(xtest)

In [61]:
accuracy_score(ytestt,ypred)

0.8360655737704918

In [63]:
age = int(input("Enter Age: "))
restbp = int(input("Enter RestBP: "))
chol = int(input("Enter Cholesterol: "))
maxhr = int(input("Enter MaxHR: "))

user_data = [[age, restbp, chol, maxhr]]

prediction = clf.predict(user_data)

print("Prediction:", prediction)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

ValueError: X has 4 features, but DecisionTreeClassifier is expecting 14 features as input.

In [62]:
confusion_matrix(ytestt,ypred)

array([[25,  4],
       [ 6, 26]])